<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('nfts', function (Blueprint $table) {
            $table->id();

            // The Wallet Address that owns/minted this NFT
            $table->string('owner_address')->index();

            // The unique 64-character hex ID generated by the XRPL (Filled after validation)
            $table->string('nft_id')->nullable()->unique();

            // Minting Details
            $table->unsignedInteger('taxon')->default(0);
            $table->text('uri')->nullable(); // Text because IPFS/Data URIs can be long
            $table->unsignedInteger('flags')->default(0);
            $table->unsignedInteger('transfer_fee')->default(0); // 0-50000

            // State Management
            $table->string('status')->default('PENDING')->index(); // PENDING, MINTED, FAILED, CONFIRMED
            $table->string('tx_hash')->nullable();
            $table->text('response')->nullable();
            $table->text('error_message')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('nfts');
    }
};
